### ISSUE TITLE
[Question] Clarification about the RPC protocol

### ISSUE THREAD

**Issue by lamafab** [deltap2p/hobbits#28]
Hello

This specification mentions the following envelope for RPC messages:

```
{ 
  'method_id': 'uint16' ## byte representing the method
  'id': 'uint64' ## id of the request
  'body': 'bytes' ## body of the request itself
}
```

Do I understand it correctly that RPC messages **always** contain the body **inside the header** and have a **body length of 0**?

Therefore, the HELLO message would look something like this (certain values adjusted, of course):

```
EWP 3 RPC 65 0
{
  "method_id": 0x01,
  "id": 1,
  "body": {
    "network_id": 1,
    "chain_id": 1,
    "latest_finalized_root": "0x000...",
    "latest_finalized_epoch": 1,
    "best_root": "0x000...",
    "best_slot": 1
  }
}
```

Also, are only RPC message bodies SSZ encoded?

Thank you

EDIT: The header field "timestamp" in GOSSIP should be `uint64` instead of `uint32`, no? This would have consistency with `0x02 GET_STATUS`

```
{
  'user_agent': 'bytes' ## the human readable name of the client, optionally with its version and other metadata
  'timestamp': 'uint64' ## the current time of the node in milliseconds since epoch
}
```

=>  https://en.wikipedia.org/wiki/Year_2038_problem

**Comment by renaynay** [comment]
Hey we fixed the spec yesterday, check this out: https://github.com/deltap2p/hobbits/blob/master/specs/spec.md#envelope

also we're gonna fix the inconsistency. Should be a uint32 across the board for timestamp. Thanks for noticing!

**Comment by lamafab** [comment]
Fantastic! About the timestamp; you should really go with `uint64`. A 32bit integer [is a bad idea](https://en.wikipedia.org/wiki/Year_2038_problem). Assuming Hobbits makes it into the final ETH2.0 draft I do think it's important to think about this. Many systems including programming languages already use `uint64` for unix time.

> The Year 2038 problem relates to representing time in many digital systems as the number of seconds passed since 1 January 1970 and storing it as a signed 32-bit binary integer. Such implementations cannot encode times after 03:14:07 UTC on 19 January 2038. Just like the Y2K problem, the Year 2038 problem is caused by insufficient capacity of the chosen storage unit.

**Comment by renaynay** [comment]
You're right, gonna change it now
